### ISSUE TITLE
/api/colortest/values not working

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch-hass-addon#5]
Hi,
I'm seeing this error in the addon logs when I send the POST request:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/swatch/swatch/http.py", line 91, in test_colors
    main_color, palette = current_app.image_processor.parse_colors_from_image(
AttributeError: 'ImageProcessor' object has no attribute 'parse_colors_from_image'
```
Addon version: 3.1.0-2717ec6

**Comment by NickM-27** [comment]
Thanks, I'll take a look and see
